### PR TITLE
Other container

### PR DESCRIPTION
**Pull request by Brammm**
Introduce the ability to use another container than the provided `PHP-DI` one.

### CODE REVIEW

**Comment by Brammm** [comment]
@exts Let me know what you think of this approach, also see [the documentation](https://github.com/starchphp/starch/blob/8c397128fa441769672ff9bffad0459357047032/README.md#using-another-container) on how to use it.

**Comment by exts** [comment]
I don't mind directly having the container as the first dependency. But you should update maybe `getContainer` to check if those interfaces exists.

**Comment by Brammm** [comment]
I've gone ahead and merged like this, the license has also been changed to MIT. So feel free to either use this as is, or fork and have your own way with it ;)

**Comment by exts** [comment]
Time to try this in my own application :)

**Comment by exts** [comment]
@Brammm if you're curious what I'm doing w/ Starch [Mixten](https://github.com/exts/Mixten) and [MixtenSkeleton](https://github.com/exts/MixtenSkeleton), hopefully starch stays around because I finally got in a good spot w/ how I want my applications to look.

**Comment by Brammm** [comment]
Good luck with the project!

**Pull request merged**
